version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=jsonplaceholder
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=8080
      - JWT_SECRET=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    depends_on:
      - db
    networks:
      - jsonplaceholder-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jsonplaceholder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jsonplaceholder-network

volumes:
  postgres-data:

networks:
  jsonplaceholder-network:
    driver: bridge 